'use strict';

// Works out how Claude should launch the boardroom's MCP server and hook, for
// whichever way this copy is running:
//
//   installed app  — the Electron exe itself, with ELECTRON_RUN_AS_NODE=1, so
//                    there is no dependency on Node being installed
//   from source    — whatever Node is running this process
//
// Both the installer and the app use this, so a config written by one is
// identical to a config written by the other.

const fs = require('node:fs');
const path = require('node:path');
const { DB_DIR } = require('./db');

const ROOT = path.join(__dirname, '..');
const SERVER_JS = path.join(ROOT, 'src', 'mcp-server.js');
const HOOK_JS = path.join(ROOT, 'hooks', 'boardroom-hook.js');

// The shim lives outside the install directory on purpose. Its path is then
// stable forever, so the hook entry in settings.json never has to be rewritten
// when the app updates — only the shim's contents change.
const BIN_DIR = path.join(DB_DIR, 'bin');
const SHIM = path.join(BIN_DIR, process.platform === 'win32' ? 'boardroom-hook.cmd' : 'boardroom-hook.sh');

function context(ctx = {}) {
  return {
    execPath: ctx.execPath || process.execPath,
    // The thing that decides how to invoke a script is whether the executable
    // is an Electron binary, NOT whether the app is packaged. The dev binary
    // in node_modules needs ELECTRON_RUN_AS_NODE every bit as much as the
    // installed one — without it Electron boots an app instead of running the
    // script, and the MCP server never speaks a word on stdout.
    isElectron:
      ctx.isElectron === undefined ? Boolean(process.versions.electron) : Boolean(ctx.isElectron),
    packaged: Boolean(ctx.packaged),
  };
}

// How to run one of our scripts.
function launcher(ctx) {
  const { execPath, isElectron } = context(ctx);
  return isElectron
    ? { command: execPath, env: { ELECTRON_RUN_AS_NODE: '1' } }
    : { command: execPath, env: {} };
}

function mcpServerEntry(ctx) {
  const { command, env } = launcher(ctx);
  const entry = { command, args: [SERVER_JS] };
  if (Object.keys(env).length) entry.env = env;
  return entry;
}

// Claude runs hooks as a shell command string, which is an awkward place to set
// an environment variable portably. A tiny generated shim sidesteps that.
function writeHookShim(ctx) {
  const { command, env } = launcher(ctx);
  fs.mkdirSync(BIN_DIR, { recursive: true });

  let body;
  if (process.platform === 'win32') {
    const sets = Object.entries(env).map(([k, v]) => `set "${k}=${v}"`).join('\r\n');
    body = [
      '@echo off',
      'rem Generated by Claude Boardroom. Rewritten on every app launch —',
      'rem edit the app, not this file.',
      sets,
      `"${command}" "${HOOK_JS}" %*`,
      '',
    ].filter(Boolean).join('\r\n');
  } else {
    const sets = Object.entries(env).map(([k, v]) => `export ${k}="${v}"`).join('\n');
    body = [
      '#!/bin/sh',
      '# Generated by Claude Boardroom. Rewritten on every app launch.',
      sets,
      `exec "${command}" "${HOOK_JS}" "$@"`,
      '',
    ].filter(Boolean).join('\n');
  }

  // Only touch the file when it actually changes, so we do not invalidate it
  // out from under a hook that is mid-run.
  let existing = null;
  try {
    existing = fs.readFileSync(SHIM, 'utf8');
  } catch {
    /* first run */
  }
  if (existing !== body) {
    fs.writeFileSync(SHIM, body);
    if (process.platform !== 'win32') fs.chmodSync(SHIM, 0o755);
  }

  return { path: SHIM, changed: existing !== body };
}

function hookCommand() {
  return `"${SHIM}"`;
}

const LOGIN_SHIM = path.join(
  BIN_DIR,
  process.platform === 'win32' ? 'boardroom-login.cmd' : 'boardroom-login.sh'
);

// A one-shot script that opens the Claude Code CLI interactively in a project
// folder, so the user can complete the login it is asking for.
//
// The folder is baked in and the file is then opened directly, rather than
// assembling a command line with a shell. `start`, cmd.exe and batch each
// re-parse quoting differently, and folder paths here routinely contain
// spaces — writing the path into a file sidesteps all of that.
function writeLoginShim(claudeBin, folder) {
  fs.mkdirSync(BIN_DIR, { recursive: true });

  const body = process.platform === 'win32'
    ? [
        '@echo off',
        'title Claude Code login',
        'rem Generated by Claude Boardroom, rewritten on each use.',
        `cd /d "${folder}"`,
        'echo Log in to Claude Code, then close this window.',
        'echo If you are not prompted automatically, type: /login',
        'echo.',
        `"${claudeBin}"`,
        'echo.',
        'echo This window can be closed.',
        'pause',
        '',
      ].join('\r\n')
    : [
        '#!/bin/sh',
        '# Generated by Claude Boardroom, rewritten on each use.',
        `cd "${folder}" || exit 1`,
        'echo "Log in to Claude Code, then close this window."',
        `exec "${claudeBin}"`,
        '',
      ].join('\n');

  fs.writeFileSync(LOGIN_SHIM, body);
  if (process.platform !== 'win32') fs.chmodSync(LOGIN_SHIM, 0o755);
  return LOGIN_SHIM;
}

// Claude Code reports "Not logged in - Please run /login" on stdout and exits
// non-zero, which otherwise reaches the user as an unexplained failed turn.
const AUTH_PATTERNS = [
  /not logged in/i,
  /please run \/login/i,
  /run `?\/login`?/i,
  /invalid api key/i,
  /authentication[ _-]?error/i,
  /oauth token (has )?expired/i,
  /session (has )?expired/i,
];

function looksLikeAuthFailure(text) {
  if (!text) return false;
  return AUTH_PATTERNS.some((re) => re.test(text));
}

module.exports = {
  ROOT,
  SERVER_JS,
  HOOK_JS,
  SHIM,
  context,
  launcher,
  mcpServerEntry,
  writeHookShim,
  hookCommand,
  writeLoginShim,
  looksLikeAuthFailure,
  LOGIN_SHIM,
};
