'use strict';

// Works out how Claude should launch the boardroom's MCP server and hook, for
// whichever way this copy is running:
//
//   installed app  — the Electron exe itself, with ELECTRON_RUN_AS_NODE=1, so
//                    there is no dependency on Node being installed
//   from source    — whatever Node is running this process
//
// Both the installer and the app use this, so a config written by one is
// identical to a config written by the other.

const fs = require('node:fs');
const path = require('node:path');
const { DB_DIR } = require('./db');

const ROOT = path.join(__dirname, '..');
const SERVER_JS = path.join(ROOT, 'src', 'mcp-server.js');
const HOOK_JS = path.join(ROOT, 'hooks', 'boardroom-hook.js');

// The shim lives outside the install directory on purpose. Its path is then
// stable forever, so the hook entry in settings.json never has to be rewritten
// when the app updates — only the shim's contents change.
const BIN_DIR = path.join(DB_DIR, 'bin');
const SHIM = path.join(BIN_DIR, process.platform === 'win32' ? 'boardroom-hook.cmd' : 'boardroom-hook.sh');

function context(ctx = {}) {
  return {
    execPath: ctx.execPath || process.execPath,
    packaged: Boolean(ctx.packaged),
  };
}

// How to run one of our scripts.
function launcher(ctx) {
  const { execPath, packaged } = context(ctx);
  return packaged
    ? { command: execPath, env: { ELECTRON_RUN_AS_NODE: '1' } }
    : { command: execPath, env: {} };
}

function mcpServerEntry(ctx) {
  const { command, env } = launcher(ctx);
  const entry = { command, args: [SERVER_JS] };
  if (Object.keys(env).length) entry.env = env;
  return entry;
}

// Claude runs hooks as a shell command string, which is an awkward place to set
// an environment variable portably. A tiny generated shim sidesteps that.
function writeHookShim(ctx) {
  const { command, env } = launcher(ctx);
  fs.mkdirSync(BIN_DIR, { recursive: true });

  let body;
  if (process.platform === 'win32') {
    const sets = Object.entries(env).map(([k, v]) => `set "${k}=${v}"`).join('\r\n');
    body = [
      '@echo off',
      'rem Generated by Claude Boardroom. Rewritten on every app launch —',
      'rem edit the app, not this file.',
      sets,
      `"${command}" "${HOOK_JS}" %*`,
      '',
    ].filter(Boolean).join('\r\n');
  } else {
    const sets = Object.entries(env).map(([k, v]) => `export ${k}="${v}"`).join('\n');
    body = [
      '#!/bin/sh',
      '# Generated by Claude Boardroom. Rewritten on every app launch.',
      sets,
      `exec "${command}" "${HOOK_JS}" "$@"`,
      '',
    ].filter(Boolean).join('\n');
  }

  // Only touch the file when it actually changes, so we do not invalidate it
  // out from under a hook that is mid-run.
  let existing = null;
  try {
    existing = fs.readFileSync(SHIM, 'utf8');
  } catch {
    /* first run */
  }
  if (existing !== body) {
    fs.writeFileSync(SHIM, body);
    if (process.platform !== 'win32') fs.chmodSync(SHIM, 0o755);
  }

  return { path: SHIM, changed: existing !== body };
}

function hookCommand() {
  return `"${SHIM}"`;
}

module.exports = {
  ROOT,
  SERVER_JS,
  HOOK_JS,
  SHIM,
  context,
  launcher,
  mcpServerEntry,
  writeHookShim,
  hookCommand,
};
